torchvision_data_path: /mnt/MegaDisc/Data/PT/
data_paths: {Imagenet-12: /data/lisa/data/ImageNet2012_jpeg}
viz: {
    font: /usr/share/fonts/truetype/liberation/LiberationSerif-Regular.ttf
}
out_path: /mnt/MegaDisc/Outs/