torchvision_data_path: /home/devon/Data/PT/
data_paths: {Imagenet-12: /data/lisa/data/ImageNet2012_jpeg}
viz: {
    font: /usr/share/fonts/truetype/liberation/LiberationSerif-Regular.ttf
}
out_path: /home/devon/Outs/